### ISSUE TITLE
stopped working jq: error (at <stdin>:1): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by markmark1** [pstadler/ticker.sh#34] opened 2023-04-20 00:05 UTC
jq: error (at <stdin>:1): Cannot iterate over null (null)

 Advice:
    Nothing found for symbol ^N225
    Lookup the right one: finance.yahoo.com/lookup
=====================================================

**Comment by jmdugan** [comment] 2023-04-20 01:09
yup yup searching for alternative sources too

**Comment by phish0r** [comment] 2023-04-20 03:34
Anyone know how to fix this yet?

**Comment by pstadler** [comment] 2023-04-20 05:00
Duplicate of #33

**Closed by pstadler** 2023-04-20 05:00 UTC
